#!/bin/sh

rm -rf ./public/*

if [ -f /.dockerenv ]; then
    hugo server --noHTTPCache --buildDrafts
else
    HUGO_IMG="hugo-template/hugo"

    docker build -t ${HUGO_IMG}:latest -f hugo.Dockerfile . 

    docker run --rm -it \
    -v $(pwd):/home/app \
    --net host \
    -u $(id -u):$(id -g) \
    ${HUGO_IMG}:latest \
    hugo server --bind=0.0.0.0 --noHTTPCache --buildDrafts --baseURL=http://$(hostname -I):1313
fi